###Registeration Page
browser=chrome
server.port=9094
spring.datasource.url=jdbc:h2:mem:company
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true


spring.security.user.name=sergey
spring.security.user.password=sergey
spring.security.user.roles=manager
url=https://www.saucedemo.com/
username=//input[@id='user-name']
usernameValue=standard_user
passwordValue=secret_sauce
password=//input[@id='password']
login=//input[@id='login-button']
addToCartButtonXpath=//button[contains(text(),'Add to cart')]
removeButton=//button[contains(text(),'Remove')]
cartIconNoOfProductAdded=(//span[contains(text(),*)])[1]
cartIcon=//a[@class='shopping_cart_link']
checkoutButton=//button[@id='checkout']
spring.devtools.restart.enabled=false
#spring.kafka.bootstrap-servers=77.37.45.154:29092,89.117.151.178:29092
spring.kafka.bootstrap-servers=localhost:9092
enable.auto.commit=true
auto.commit.interval.ms=6000
spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer