name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t selenium-docker .
          docker run -p 8080:80 --name mycontainer selenium-docker
          mkdir reports
          ls -ltr
          echo "the container id is "
          docker ps
          docker container ls
          exit
          docker cp c5d407310c2a:app/target/cucumber-reports/report.html reports/
          cd reports
          ls -ltr