name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t selenium-docker .
          docker run -p 8080:80 --name mycontainer selenium-docker
          ls -ltr

      - name: Download report artifact
        run: |
          mkdir reports
          docker cp mycontainer:app/target/cucumber-reports/report.html reports/
          Thread.sleep(30000L)

      - name: test results
        uses: dorny/test-reporter@v1
        with:
          artifact: AutomationTesting            # artifact name
          name: Cucumber Report                  # Name of the check run which will be created
          path: reports                     # Path to test results (inside artifact .zip)
          reporter: jest-junit
