name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t selenium-docker .
          docker run -p 8080:80 --name mycontainer selenium-docker
          ls -ltr

      - name: Download report artifact
        run: |
          mkdir reports
          docker cp mycontainer:app/target/cucumber-reports/report.html reports/
          docker ps
          exit
          docker cp 5092992624:app/target/cucumber-reports/report.html reports/